name: xeus-octave-wasm-build
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  # Xeus-Octave
  - cmake
  - make
  - pkg-config
  - emscripten_emscripten-wasm32==3.1.73
  # JupyterLite
  - jupyterlite-core
  - jupyter_server
  - jupyterlite-xeus
